BUNDLE_NAME=wc-metric
BUNDLE_VERSION=0.0.1
BUNDLE_MANIFEST_NAME=manifest

EXTRA_CP=../../alitheia/tds/src:../../alitheia/fds/src:../../alitheia/logger/src/:../abstract-metric/src:../../alitheia/db/src:

include ../Makefile-sub.inc

