//Alitheia.idl
module alitheia
{
  interface Logger
  {
    string debug( in string text );
    string info( in string text );
    string warn( in string text );
    string error( in string text );
  };
};
