//Alitheia.idl
module alitheia
{
  interface Core
  {
    long registerMetric( in string name );
    void unregisterMetric( in long id );
  };

  interface Logger
  {
    void debug( in string logger, in string text );
    void info( in string logger, in string text );
    void warn( in string logger, in string text );
    void error( in string logger, in string text );
  };

  interface Metric
  {
    // Get information about the metric author
    string getAuthor();
    // Get a free text description of what this metric calculates
    string getDescription();
    // Get the metric name
    string getName();
    // Get the metric version. Free from text.
    string getVersion();
    /* Generic run plug-in method
     * Returns a XML-serialized MetricResult */
    string getResult(); 
    // Get the date this version of the metric has been installed
    string getDateInstalled();
  };
};
