# This Makefile is part of the Alitheia system produced by the SQO-OSS
# consortium and is covered by the same LICENSE as the rest of the system:
# the 2-Clause FreeBSD license which you may find in the LICENSE file
# in the devel/trunk/ directory of the Alitheia development repository.

# This Makefile contains the configuation settings
# for the Alitheia system that are shared across all
# of the Makefiles. Most of these may be changed;
# the preferred way of changing the settings is
# to set them in a file Makefile.config.local in the
# top-level source directory for Alitheia. 

# Override every setting in here through Makefile.config.local
-include $(TOP_SRCDIR)/Makefile.config.local

###
#
# Configurable settings - directories
#

# The directory where the system is assembled in order to run.
# The default is the equinox/ directory which is already part
# of the checkout.
PREFIX?=$(TOPDIR)/equinox

###
#
# Configurable settings - commands
#

# Java runtime.
JAVA_CMD?=java
JAVA_ARGS?=
JAVA?=$(JAVA_CMD) $(JAVA_ARGS)


# Command to run Maven (at all). The default is the setting
# under Solaris with a Maven 2.0.8 install. Most sensible
# systems can use MAVEN_CMD=mvn instead in Makefile.config.local.
MAVEN_CMD?=JAVA_HOME=/usr /opt/apache-maven-2.0.8/bin/mvn
# Arguments passed to Maven; these should set topdir.
# because those are referred to in the POM files.
MAVEN_ARGS?=-Dtopdir=$(TOPDIR)
# Command for Maven when building Alitheia.
MAVEN?=$(MAVEN_CMD) $(MAVEN_ARGS)

# A means to quiet the output from commands
QUIET?=> /dev/null

###
#
# Non-configurable settings
#

# Top of the source tree; derived from the TOP_SRCDIR which is a relative dir.
TOPDIR=$(shell cd $(TOP_SRCDIR) && pwd)
# Maven repository in the source tree.
REPODIR=$(shell cd $(TOP_SRCDIR)/.. && test -d sqoossrepo && pwd)

