# This Makefile is part of the Alitheia system produced by the SQO-OSS
# consortium and is covered by the same LICENSE as the rest of the system:
# the 2-Clause FreeBSD license which you may find in the LICENSE file
# in the devel/trunk/ directory of the Alitheia development repository.

# This Makefile contains the configuation settings
# for the Alitheia system that are shared across all
# of the Makefiles. Most of these may be changed;
# the preferred way of changing the settings is
# to set them in a file Makefile.config.local in the
# top-level source directory for Alitheia.

# Override every setting in here through Makefile.config.local
-include $(TOP_SRCDIR)/Makefile.config.local

UNAME=$(shell uname)

###
#
# Configurable settings - directories
#

# The directory where the system is assembled in order to run.
# The default is the equinox/ directory which is already part
# of the checkout.
PREFIX?=$(TOPDIR)/equinox

###
#
# Configurable settings - commands
#

# Java runtime.
JAVA_CMD?=java
JAVA_ARGS?=
JAVA?=$(JAVA_CMD) $(JAVA_ARGS)


# Root of the Maven installation; the installation instructions
# for Maven say to set it, but that's a little overly optimistic.
M2_HOME?=/usr
# Command to run Maven (at all).
MAVEN_CMD?=mvn

# Arguments passed to Maven; these are only for special
# compile purposes and not needed normally.
MAVEN_ARGS?=
# Command for Maven when building Alitheia.
MAVEN?=$(MAVEN_CMD) $(MAVEN_ARGS)

# A means to quiet the output from commands
QUIET?=> /dev/null

# pwd command
# on windows with msys, the command should return windows-syntax paths (ie. use the -W option), since that's what maven expects
PWD_CMD?=pwd

###
#
# Tomcat settings
#
# In the webui directory, we create a WAR of the code for the Alitheia
# public-facing website. This can be deployed to a tomcat instance
# through 'make install' but then (a) we need to know where in the file-
# system the tomcat files live and (b) the tomcat instance needs to
# be configured to automatically reload the WAR file.
#

# Do we want tomcat based things to be installed at all?
# If you don't have tomcat running, leave this set to NO.
WITH_TOMCAT?=YES

# Top directory of a tomcat installation
TOMCAT_BASE?=$(TOPDIR)/tomcat
# The webapps directory of a tomcat installation
TOMCAT_WEBAPPS?=$(TOMCAT_BASE)/webapps

###
#
# Fetch (http client)
#
# Usage:
#     $(FETCH) <url> <file>
# Retrieves the given URL (http-only) and stores it in the given file.
# The default is this Java-based solution, because it's available
# within the source tree. You may want to substiture curl or fetch.
#
# This is a Java tool which fetches a URL and prints the content to stdout.
# You might want to replace it with fetch on a FreeBSD system.
FETCH?=java -cp $(TOP_SRCDIR)/tools/GetHTML.jar GetHTML

###
#
# Documentation settings
#
# Set to the location of the docbook stylesheets on your system
XSLT_DOCBOOK?=/usr/local/share/xsl/docbook-xsl



###
#
# GNU tar
#
ifeq (SunOS,$(shell uname))
TAR?=gtar
else
TAR?=tar
endif

###
#
# Non-configurable settings
#

# Top of the source tree; derived from the TOP_SRCDIR which is a relative dir.
TOPDIR=$(shell cd $(TOP_SRCDIR) && $(PWD_CMD))
# Maven repository in the source tree.
REPODIR=$(shell cd $(TOP_SRCDIR)/.. && test -d sqoossrepo && $(PWD_CMD))


MAKEFILE_CONFIG_INCLUDED=YES
