include $(TOP_SRCDIR)/Makefile.config

all : build

build :
	$(MAVEN) compile install

clean : clean-dir
	rm -rf */build */target

clean-dir :

install :
	$(MAVEN) package

help :
	@echo $(MAVEN)

.PHONY : all build clean clean-dir install help

