include $(TOP_SRCDIR)/Makefile.config

all : build

build : build-dir
	$(MAVEN) package install

build-dir :

clean : clean-dir
	rm -rf build target

clean-dir :

install :
	cp target/*.jar $(PREFIX)

help :
	@echo $(MAVEN)

.PHONY : all build clean clean-dir install help

