include $(TOP_SRCDIR)/Makefile.config

all : build

build :
	$(MAVEN) compile install

clean : clean-dir
	rm -rf */build */target

clean-dir :

install :
	for i in $(SUBDIRS) ; do cp $$i/target/*.jar $(PREFIX) ; done

help :
	@echo $(MAVEN)

.PHONY : all build clean clean-dir install help

