# This is not really part of the build system, just a convenience
# way down here in the source tree.

JAVA_LINT=-Xlint

build :
	javac $(JAVA_LINT) -cp ../../../../lib/eu.sqooss.scl_0.0.1.jar *\.java

clean :
	rm *\.class

