/*
 * This file is part of the Alitheia system, developed by the SQO-OSS
 * consortium as part of the IST FP6 SQO-OSS project, number 033331.
 *
 * Copyright 2007-2008 by the SQO-OSS consortium members <info@sqo-oss.eu>
 * Copyright 2007-2008 by Adriaan de Groot <groot@kde.org>
 *
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *
 *     * Redistributions in binary form must reproduce the above
 *       copyright notice, this list of conditions and the following
 *       disclaimer in the documentation and/or other materials provided
 *       with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

package eu.sqooss.impl.service.webadmin;

import java.util.Hashtable;

import javax.servlet.Servlet;
import javax.servlet.http.HttpServlet;

import org.apache.velocity.app.VelocityEngine;
import org.apache.velocity.runtime.RuntimeConstants;
import org.osgi.framework.BundleContext;
import org.osgi.framework.ServiceReference;
import org.osgi.service.http.HttpContext;

import eu.sqooss.core.AlitheiaCore;
import eu.sqooss.service.logging.Logger;
import eu.sqooss.service.messaging.MessagingService;
import eu.sqooss.service.webadmin.WebadminService;

import org.ops4j.pax.web.service.WebContainer;

/**
 * This is the service which provides a web-based administration
 * interface. This user interface is used for the addition and removal
 * of projects from Alitheia Core and likewise for metric
 * plugins. Users of the WebAdmin interface are also able to receive
 * basic system information such as uptime, number of running/failed
 * jobs, etc.
 */
public class WebadminServiceImpl implements WebadminService {

    /**
     * The Velocity Engine is used to to provide services for
     * dynamically loading content into the page templates
     */
    private VelocityEngine ve;
    private NotifyAdminMessageSender messageSender;

    /**
     * Used for logging all system messages generated by the WebAdmin
     */
    private Logger logger = null;

    /**
     * This String is used to represent the current "message of the
     * day" available in the Alitheia Core
     */
    private String messageOfTheDay = null;

    public WebadminServiceImpl(BundleContext bc,
            MessagingService messagingService, Logger logger) {
        ServiceReference srcore = bc.getServiceReference(AlitheiaCore.class.getName());
        AlitheiaCore core = (AlitheiaCore) bc.getService(srcore);

        //Get the LogManager and Logger objects
        logger = core.getLogManager().createLogger(
                    Logger.NAME_SQOOSS_WEBADMIN);

        // Get a reference to the HTTPService, and then its object
        //srefHTTPService = bc.getServiceReference(HttpService.class.getName());
        
        ServiceReference webContainerRef = bc.getServiceReference(WebContainer.class.getName());
        if (webContainerRef == null) {
            logger.error("Could not start the WebAdmin service");
            return;
        }

        WebContainer webContainer = (WebContainer) bc.getService(webContainerRef);
        HttpContext httpContext = webContainer.createDefaultHttpContext();

        /*if (srefHTTPService != null) {
            sobjHTTPService = (HttpService) bc.getService(srefHTTPService);
        }
        else {
            logger.error("Could not find a HTTP service!");
        }*/

        initVelocity();
        messageSender = new NotifyAdminMessageSender(messagingService, ve);
        // Register the front-end servlets
        if (webContainer != null) {
            HttpServlet servlet = new AdminServlet(bc, this, logger, ve);
            try {
            	webContainer.registerServlet("/", 
                    (Servlet) servlet,
                    new Hashtable(),
                    httpContext);
            }
            catch (Exception e) {
                logger.error("AdminServlet",e);
            }

            try {
            	webContainer.registerServlet(
                        "/ws",
                        (Servlet) new AdminWS(bc),
                        new Hashtable(),
                        httpContext);
            }
            catch (Exception e) {
                logger.error("AdmWS", e);
            }
        }
    }

    /**
     * Retrieves the "message of the day" String
     *
     * @return the message as a String
     */
    public String getMessageOfTheDay() {
        return messageOfTheDay;
    }

    /**
     * Sets the "message of the day" String
     *
     * @param s The text to be used as the "message of the day"
     */
    public void setMessageOfTheDay(String s) {
        messageOfTheDay = s;
    }

    /**
     * @see eu.sqooss.service.webadmin.WebadminService#notifyAdmin(String, String, String)
     */
    public boolean notifyAdmin(String title,
            String messageBody, String fromEmailAddress) {
        return messageSender.sendMessage(messageBody, title, fromEmailAddress);
    }

    /*
     * The utility method used for the initialization of the velocity engine.
     */
    private void initVelocity() {
        try {
            ve = new VelocityEngine();
            ve.setProperty("runtime.log.logsystem.class",
                           "org.apache.velocity.runtime.log.SimpleLog4JLogSystem");
            ve.setProperty("runtime.log.logsystem.log4j.category",
                           Logger.NAME_SQOOSS_WEBADMIN);
            String resourceLoader = "classpath";
            ve.setProperty(RuntimeConstants.RESOURCE_LOADER, resourceLoader);
            ve.setProperty(resourceLoader + "." + RuntimeConstants.RESOURCE_LOADER + ".class",
            "org.apache.velocity.runtime.resource.loader.ClasspathResourceLoader");
        }
        catch (Exception e) {
            logger.error("Velocity initialization",e);
        }
    }
}


// vi: ai nosi sw=4 ts=4 expandtab

