package eu.sqooss.impl.service.alitheia;


/**
* eu/sqooss/impl/service/alitheia/CorePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Alitheia.idl
* den 20 december 2007 kl 13:07 CET
*/

public abstract class CorePOA extends org.omg.PortableServer.Servant
 implements eu.sqooss.impl.service.alitheia.CoreOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registerMetric", new java.lang.Integer (0));
    _methods.put ("unregisterMetric", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // alitheia/Core/registerMetric
       {
         String name = in.read_string ();
         int $result = (int)0;
         $result = this.registerMetric (name);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // alitheia/Core/unregisterMetric
       {
         int id = in.read_long ();
         this.unregisterMetric (id);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:alitheia/Core:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Core _this() 
  {
    return CoreHelper.narrow(
    super._this_object());
  }

  public Core _this(org.omg.CORBA.ORB orb) 
  {
    return CoreHelper.narrow(
    super._this_object(orb));
  }


} // class CorePOA
