package eu.sqooss.impl.service.alitheia;


/**
* eu/sqooss/impl/service/alitheia/CoreOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Alitheia.idl
* den 20 december 2007 kl 13:07 CET
*/

public interface CoreOperations 
{
  int registerMetric (String name);
  void unregisterMetric (int id);
} // interface CoreOperations
