package eu.sqooss.impl.service.alitheia;


/**
* eu/sqooss/impl/service/alitheia/LoggerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Alitheia.idl
* den 13 december 2007 kl 17:54 CET
*/

public interface LoggerOperations 
{
  String debug (String text);
  String info (String text);
  String warn (String text);
  String error (String text);
} // interface LoggerOperations
