package eu.sqooss.impl.service.alitheia;


/**
* eu/sqooss/impl/service/alitheia/LoggerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Alitheia.idl
* den 13 december 2007 kl 17:54 CET
*/

public abstract class LoggerPOA extends org.omg.PortableServer.Servant
 implements eu.sqooss.impl.service.alitheia.LoggerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("debug", new java.lang.Integer (0));
    _methods.put ("info", new java.lang.Integer (1));
    _methods.put ("warn", new java.lang.Integer (2));
    _methods.put ("error", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // alitheia/Logger/debug
       {
         String text = in.read_string ();
         String $result = null;
         $result = this.debug (text);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // alitheia/Logger/info
       {
         String text = in.read_string ();
         String $result = null;
         $result = this.info (text);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // alitheia/Logger/warn
       {
         String text = in.read_string ();
         String $result = null;
         $result = this.warn (text);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // alitheia/Logger/error
       {
         String text = in.read_string ();
         String $result = null;
         $result = this.error (text);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:alitheia/Logger:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Logger _this() 
  {
    return LoggerHelper.narrow(
    super._this_object());
  }

  public Logger _this(org.omg.CORBA.ORB orb) 
  {
    return LoggerHelper.narrow(
    super._this_object(orb));
  }


} // class LoggerPOA
