package eu.sqooss.impl.service.alitheia;


/**
* eu/sqooss/impl/service/alitheia/Logger.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Alitheia.idl
* den 14 december 2007 kl 14:25 CET
*/

public interface Logger extends LoggerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Logger
