package eu.sqooss.impl.service.alitheia;


/**
* eu/sqooss/impl/service/alitheia/LoggerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Alitheia.idl
* den 14 december 2007 kl 13:02 CET
*/

public interface LoggerOperations 
{
  void debug (String text);
  void info (String text);
  void warn (String text);
  void error (String text);
} // interface LoggerOperations
