package eu.sqooss.impl.service.alitheia;


/**
* eu/sqooss/impl/service/alitheia/MetricHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Alitheia.idl
* den 20 december 2007 kl 13:07 CET
*/

abstract public class MetricHelper
{
  private static String  _id = "IDL:alitheia/Metric:1.0";

  public static void insert (org.omg.CORBA.Any a, eu.sqooss.impl.service.alitheia.Metric that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static eu.sqooss.impl.service.alitheia.Metric extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (eu.sqooss.impl.service.alitheia.MetricHelper.id (), "Metric");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static eu.sqooss.impl.service.alitheia.Metric read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_MetricStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, eu.sqooss.impl.service.alitheia.Metric value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static eu.sqooss.impl.service.alitheia.Metric narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof eu.sqooss.impl.service.alitheia.Metric)
      return (eu.sqooss.impl.service.alitheia.Metric)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      eu.sqooss.impl.service.alitheia._MetricStub stub = new eu.sqooss.impl.service.alitheia._MetricStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static eu.sqooss.impl.service.alitheia.Metric unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof eu.sqooss.impl.service.alitheia.Metric)
      return (eu.sqooss.impl.service.alitheia.Metric)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      eu.sqooss.impl.service.alitheia._MetricStub stub = new eu.sqooss.impl.service.alitheia._MetricStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
