package eu.sqooss.impl.service.alitheia;


/**
* eu/sqooss/impl/service/alitheia/MetricOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Alitheia.idl
* den 20 december 2007 kl 13:07 CET
*/

public interface MetricOperations 
{

  // Get information about the metric author
  String getAuthor ();

  // Get a free text description of what this metric calculates
  String getDescription ();

  // Get the metric name
  String getName ();

  // Get the metric version. Free from text.
  String getVersion ();

  /* Generic run plug-in method
       * Returns a XML-serialized MetricResult */
  String getResult ();

  // Get the date this version of the metric has been installed
  String getDateInstalled ();
} // interface MetricOperations
