package eu.sqooss.impl.service.alitheia;

/**
* eu/sqooss/impl/service/alitheia/MetricHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Alitheia.idl
* den 20 december 2007 kl 13:07 CET
*/

public final class MetricHolder implements org.omg.CORBA.portable.Streamable
{
  public eu.sqooss.impl.service.alitheia.Metric value = null;

  public MetricHolder ()
  {
  }

  public MetricHolder (eu.sqooss.impl.service.alitheia.Metric initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = eu.sqooss.impl.service.alitheia.MetricHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    eu.sqooss.impl.service.alitheia.MetricHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return eu.sqooss.impl.service.alitheia.MetricHelper.type ();
  }

}
