//Alitheia.idl
module alitheia
{
  interface Core
  {
    // registers a metric accesible by 'name' in the ORB at the core
    // returns an id which can be used to unregister the metric again
    long registerMetric( in string name );
    // unregisters a metric previously registered
    void unregisterMetric( in long id );

    long registerJob( in string name );
    void enqueueJob( in string name );
    void unregisterJob( in long id );
    void addJobDependency( in string job, in string dependency );
    void waitForJobFinished( in string name );
  };

  interface Job
  {
    long priority();
    void run();
    enum JobState
    {
        Created,
        Queued,
        Running,
        Finished,
        Error
    };
    void setState( in JobState state );
  };

  interface Logger
  {
    // prints the debug message text to logger
    void debug( in string logger, in string text );
    // prints the info message text to logger
    void info( in string logger, in string text );
    // prints the warn message text to logger
    void warn( in string logger, in string text );
    // prints the error message text to logger
    void error( in string logger, in string text );
  };

  struct ProjectVersion;
  struct ProjectFile;
  typedef sequence<ProjectFile> ProjectFileList;
  typedef sequence<ProjectVersion> ProjectVersionList;

  struct StoredProject
  {
    string name;
    string website;
    string contact;
    string bugs;
    string repository;
    string mail;
  };

  struct ProjectVersion
  {
    StoredProject project;
    long version;
    long timeStamp;
  };

  struct ProjectFile
  {
    string name;
    ProjectVersion projectVersion;
    string status;
  };

  struct Tag
  {
    ProjectVersion projectVersion;
    string name;
  };

  struct FileGroup
  {
     string name;
     string subPath;
     string regex;
     long recalcFreq;
     string lastUsed;
     ProjectVersion projectVersion;
  };

  interface AbstractMetric
  {
    // Get information about the metric author
    string getAuthor();
    // Get a free text description of what this metric calculates
    string getDescription();
    // Get the metric name
    string getName();
    // Get the metric version. Free form text.
    string getVersion();
    // Get the date this version of the metric has been installed
    string getDateInstalled();
  };

  interface ProjectVersionMetric : AbstractMetric
  {
    /* Generic run plug-in method
     * Returns a XML-serialized MetricResult */
    string getResult( in ProjectVersion projectVersion ); 
  };
  interface StoredProjectMetric : AbstractMetric
  {
    /* Generic run plug-in method
     * Returns a XML-serialized MetricResult */
    string getResult( in StoredProject storedProject ); 
  };
  interface ProjectFileMetric : AbstractMetric
  {
    /* Generic run plug-in method
     * Returns a XML-serialized MetricResult */
    string getResult( in ProjectFile projectFile ); 
  };
  interface FileGroupMetric : AbstractMetric
  {
    /* Generic run plug-in method
     * Returns a XML-serialized MetricResult */
    string getResult( in FileGroup fileGroup ); 
  };
};
