      <div id="sidebar">
        <fieldset id="status">
          <legend>$tr.label("status")</legend>
          <ul>
            <li class="uptime">$tr.label("uptime") : $UPTIME</li>
            <li class="queue">$tr.label("queue_length") : $QUEUE_LENGTH</li>
          </ul>
        </fieldset>
        $STATUS_JOBS
        $OPTIONS
      </div>
      <div id="footer">
        <p>
        $COPYRIGHT
        </p>
      </div>
