BUNDLE_NAME=core
BUNDLE_VERSION=0.0.1
BUNDLE_MANIFEST_NAME=core

EXTRA_CP=../../equinox/org.apache.commons.codec_1.3.0.jar:../../equinox/org.apache.log4j_1.2.15.jar:../../equinox/javax.servlet_2.4.0.v200612120446.jar

include ../Makefile-sub.inc

