BUNDLE_NAME=productivity-metric
BUNDLE_VERSION=0.0.1
BUNDLE_MANIFEST_NAME=productivitymetric

EXTRA_CP=../../alitheia/tds/src:../../alitheia/logger/src/:../../equinox/javax.servlet_2.4.0.v200612120446.jar:../../extlibs/com/svnkit/svnkit/1.1.4/svnkit-1.1.4.jar:

include ../Makefile-sub.inc

