BUNDLE_NAME=productivity-metric
BUNDLE_VERSION=0.0.1
BUNDLE_MANIFEST_NAME=productivitymetric

EXTRA_CP=../../alitheia/tds/src:../../alitheia/logger/src/:../abstract-metric/src:../../alitheia/db/src:../../alitheia/fds/src:../../alitheia/scheduler/src:../../alitheia/util/src:../../sharedlibs/result/src

include ../Makefile-sub.inc

