#!/bin/bash
# /*
# * This file is part of the Alitheia system, developed by the SQO-OSS
# * consortium as part of the IST FP6 SQO-OSS project, number 033331.
# *
# * Copyright 2007-2008 by the SQO-OSS consortium members <info@sqo-oss.eu>
# *
# * Redistribution and use in source and binary forms, with or without
# * modification, are permitted provided that the following conditions are
# * met:
# *
# *     * Redistributions of source code must retain the above copyright
# *       notice, this list of conditions and the following disclaimer.
# *
# *     * Redistributions in binary form must reproduce the above
# *       copyright notice, this list of conditions and the following
# *       disclaimer in the documentation and/or other materials provided
# *       with the distribution.
# *
# * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# *
# */

# Usage fetch_changed basename URL current daysold | history fromdate todate   

bts_url=$(echo $2| cut -f 1 -d "|")
product=$(echo $2| cut -f 2 -d "|")
project=$1
argsok=0
fullname=$project'_'$product
if (test $3 = 'current')
then
	daysold=$4
	from_date=$(date --date="$daysold days ago" +%Y-%m-%d)
	to_date='now'
	argsok=1
elif (test $3 = history)
then
	from_date=$4
	to_date=$5
	argsok=1
fi
if (test $argsok -eq 1)
then
	wget --quiet --no-check-certificate -O tmpfs/$fullname.csv "$bts_url"'buglist.cgi?product='$product'&ctype=csv&query_format=advanced&short_desc_type=allwordssubstr&short_desc=&long_desc_type=substring&long_desc=&bug_file_loc_type=allwordssubstr&bug_file_loc=&keywords_type=allwords&keywords=&bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=RESOLVED&bug_status=VERIFIED&bug_status=CLOSED&emailassigned_to1=1&emailtype1=substring&email1=&emailassigned_to2=1&emailreporter2=1&emailcc2=1&emailtype2=substring&email2=&bugidtype=include&bug_id=&votes=&chfieldfrom='$from_date'&chfieldto='$to_date'&chfieldvalue=&cmdtype=doit&order=Reuse+same+sort+as+last+time&field0-0-0=%255BBug+creation%255D&type0-0-0=noop&value0-0-0='
	uniq tmpfs/$fullname".csv" > tmpfs/$fullname".csv.un"
	rm tmpfs/$fullname".csv"
	mv tmpfs/$fullname".csv.un" tmpfs/$fullname".csv"
	
	grep -v "bug_id"  tmpfs/$fullname".csv" | cut -f 1 -d ","  > tmpfs/$fullname"_id.tmp"
	rm -f tmpfs/$bts_url".lst" >/dev/null 2>/dev/null
	while read line
	do
		rnd=$(($RANDOM * $RANDOM))
		rnd=$(printf "%012d" $rnd) 
		echo $rnd'|'$project'|'$product'|'$bts_url'|'"${line}" >> tmpfs/$fullname.lst
	done < <(cat tmpfs/$fullname"_id.tmp")
	bugsfound=$(cat tmpfs/$fullname"_id.tmp"| wc -l)
	echo -n $bugsfound
else
	echo Invalid Periods
	echo 'Usage fetch_changed basename URL current daysold | history fromdate todate (+%Y-%m-%d format)' 
fi
