#!/bin/bash
# /*
# * This file is part of the Alitheia system, developed by the SQO-OSS
# * consortium as part of the IST FP6 SQO-OSS project, number 033331.
# *
# * Copyright 2007-2008 by the SQO-OSS consortium members <info@sqo-oss.eu>
# *
# * Redistribution and use in source and binary forms, with or without
# * modification, are permitted provided that the following conditions are
# * met:
# *
# *     * Redistributions of source code must retain the above copyright
# *       notice, this list of conditions and the following disclaimer.
# *
# *     * Redistributions in binary form must reproduce the above
# *       copyright notice, this list of conditions and the following
# *       disclaimer in the documentation and/or other materials provided
# *       with the distribution.
# *
# * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# *
# */

# bugripper home
bug_home="/home/sgrig/bugripper"
cd $bug_home
. configure
#This Hard coded date is the date crontab started executing weekly the current project_looper
#Time distance from now is calculated and reverse distanced week from this date in the past is fetched.
# eg in 6 months from now you will have 12 months history
# You can change the formulas of past_s and past_e so to get more depth in past data per week iteration 
now_date=$(date +%s)
past_week=$((($now_date-$start_date)/604800))
past_s=$((7*2*$past_week))
past_e=$((7*((2*$past_week)-1)))
s_Date=$(date --date="$past_s days ago" +%Y-%m-%d)
e_Date=$(date --date="$past_e days ago" +%Y-%m-%d)
echo $s_Date $e_Date
./project_looper_history $s_Date $e_Date
