#!/bin/bash
# /*
# * This file is part of the Alitheia system, developed by the SQO-OSS
# * consortium as part of the IST FP6 SQO-OSS project, number 033331.
# *
# * Copyright 2007-2008 by the SQO-OSS consortium members <info@sqo-oss.eu>
# *
# * Redistribution and use in source and binary forms, with or without
# * modification, are permitted provided that the following conditions are
# * met:
# *
# *     * Redistributions of source code must retain the above copyright
# *       notice, this list of conditions and the following disclaimer.
# *
# *     * Redistributions in binary form must reproduce the above
# *       copyright notice, this list of conditions and the following
# *       disclaimer in the documentation and/or other materials provided
# *       with the distribution.
# *
# * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# *
# */



# bugripper home
bug_home="/home/sgrig/bugripper"
cd $bug_home
. configure

date
dirlist=$(ls $data_path)
for project in $dirlist
do
	if (test -f $data_path"/"$project"/info.txt")
	then
	
	echo -n $project " " 
#bts line in info.txt  should be bts>URLendingslash|productname
		if (grep 'bts>' $data_path"/"$project"/info.txt" >/dev/null 2>/dev/null)
		then
			if !(test -d $data_path"/"$project"/bugs")
			then
				mkdir $data_path"/"$project"/bugs"	
			fi
			sleep 10
			bts=$(grep 'bts>' $data_path"/"$project"/info.txt"|cut -f 2 -d ">")
			./fetch_changed $project $bts current $days_ago 
		fi
	echo " bugs changed" in last $days_ago days 
	fi
done
rm -f tmpfs/current_unsorted_list.idx
cat tmpfs/*.lst >> tmpfs/current_unsorted_list.idx
sort  tmpfs/current_unsorted_list.idx > tmpfs/current_sorted_list.idx
rm -f tmpfs/current_unsorted_list.idx
rm -f tmpfs/*.lst
rm -f tmpfs/*_id.tmp
rm -f tmpfs/*.csv
