# This is a GNU Makefile

# This Makefile is part of the Alitheia system produced by the SQO-OSS
# consortium and is covered by the same LICENSE as the rest of the system:
# the 2-Clause FreeBSD license which you may find in the LICENSE file.

# This is an intermediate Makefile in the Alitheia build system. It just
# passes targets on to the sub-directories. You may invoke a Maven build
# by setting WITH_MAVEN to a non-empty value.

SUBDIRS=idl \
	corbaservice

#
# END OF USER CONFIGURABLE AREA
#
###

TOP_SRCDIR=..

include $(TOP_SRCDIR)/Makefile.common


