BUNDLE_NAME=updater
BUNDLE_VERSION=0.0.1

EXTRA_CP=../scheduler/src:../db/src:../tds/src:../logger/src/:../../equinox/javax.servlet_2.4.0.v200612120446.jar:../../extlibs/org/hibernate/core/3.2.5/core-3.2.5.jar:

include ../Makefile-sub.inc

