BUNDLE_NAME=webadmin
BUNDLE_VERSION=0.0.1

EXTRA_CP=../tds/src:../db/src:../logger/src/:../util/src:../../equinox/javax.servlet_2.4.0.v200612120446.jar:../../extlibs/org/hibernate/core/3.2.5/core-3.2.5.jar:

include ../Makefile-sub.inc

